server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tearzhao/repo_zyl_spring-cloud-config  # 配置git仓库的地址
          #uri: https://github.com/ityouknow/spring-cloud-examples # https://github.com/ityouknow/spring-cloud-starter/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:  #tearzhao@163.com                                        # git仓库的账号
          password:  #zyl123456                                  # git仓库的密码